apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: d-lama-service-database
spec:
  authSecret:
    name: d-lama-service-database-auth
  coordinator:
    resources:
      limits:
        cpu: 25m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 64Mi
  monitor:
    agent: prometheus.io/operator
    prometheus:
      serviceMonitor:
        interval: 10s
        labels:
  podTemplate:
    spec:
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
  replicas: 1
  standbyMode: Warm
  storage:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    storageClassName: data-hot
  storageType: Durable
  terminationPolicy: Halt
  version: "14.2"
