apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: d-lama-service-database
spec:
  storageClassName: "cinder-csi-ssd"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
