apiVersion: v1
kind: Service
metadata:
  name: d-lama-service-database
  labels:
    app: d-lama-service-database
spec:
  ports:
    - port: 3306
  selector:
    app: d-lama-service-database
    tier: mysql
  type: ClusterIP
