apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dlama-prod

commonLabels:
  env: pro

resources:
- ../../base
- config.yaml

replicas:
- count: 1
  name: d-lama-webapp

patchesStrategicMerge:
- imageversion.yaml
- patches/service-monitor.yaml

images:
- digest: sha256:0000000000000000000000000000000000000000000000000000000000000000 
  name: d-lama-webapp-image
  newName: feuerdave/d-lama-webapp
