apiVersion: v1
kind: Service
metadata:
  name: d-lama-service
spec:
  ports:
    - port: 80
      targetPort: http
      name: http
  type: ClusterIP
  selector:
    app.kubernetes.io/component: deployment
