apiVersion: v1
kind: Service
metadata:
  name: d-lama-service
spec:
  ports:
    - port: 8080
      targetPort: http
      name: http
    - port: 5000
      targetPort: grpc
      name: grpc
  selector:
    app.kubernetes.io/component: deployment