apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dlama-stage

commonLabels:
  env: sta

replicas:
- count: 1
  name: structurizr-lite

resources:
- ../../base
- config.yaml
- ingress.yaml

patchesStrategicMerge:
- imageversion.yaml
- patches/service-monitor.yaml
    
images:
-  name: structurizr/lite
   newTag: latest
