apiVersion: apps/v1
kind: Deployment
metadata:
  name: structurizr-lite
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: 'RollingUpdate'
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      logoutfmt: json
      app.kubernetes.io/component: deployment
  template:
    metadata:
      labels:
        logoutfmt: json
        app.kubernetes.io/component: deployment
    spec:
      containers:
      - name: structurizr-lite
        image: structurizr/lite
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: structurizr-storage
          mountPath: /usr/local/structurizr
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
      volumes:
      - name: structurizr-storage
        persistentVolumeClaim:
          claimName: structurizr-pvc
