apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: structurizr-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
