apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: d-lama-webapp
spec:
  selector:
    matchLabels:
      app: d-lama-webapp
      app/component: d-lama
  endpoints:
    - port: https
