apiVersion: v1
kind: Service
metadata:
  name: d-lama-webapp
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    app.kubernetes.io/component: deployment